### ISSUE TITLE
Integrating a menu

### ISSUE THREAD

**Issue by Dax-Ur** [nicolas-garcia/Plugin.BackgroundService#12]
I've been testing this plugin and it works pretty well. I've only faced a little problem after rebooting my phone.  I guess the service gets shut down after that. Anyway, I 'm practically starting to work with Xamarin and I've been trying to integrate a hamburguer menu into this project, and turn the service main page (the one with two buttons) into a settings page inside the menu, but it's really hard. How can I do that?

**Comment by nicolas-garcia** [comment]
Are you trying to convert the sample app into a real app?

I know the app get shut downed after the reboot, I should be listening to the reboot on Android, but I am pretty sure it is not possible on iOS.

**Comment by Dax-Ur** [comment]
Yeah, kind of. I'm giving my first steps on Xamarin.
So it's really possible to run the background service whenever the phone is turned on or rebooted?

**Comment by nicolas-garcia** [comment]
Yes you can create a broadcast listener for the boot action:
https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/broadcast-receivers

For your first steps to Xamarin, I suggest reading the official documentation ;)
https://docs.microsoft.com/en-us/xamarin/#pivot=xamarin-forms

Have fun with Xamarin!

I will close this issue now. Feel free to open a new one if you have an issue with this plugin.
