### ISSUE TITLE
A more customizable service

### ISSUE THREAD

**Issue by Dax-Ur** [nicolas-garcia/Plugin.BackgroundService#15]
Hi! I've been practicing a lot with this project in the last few months, but I've found it's a little hard to implement another code rather than showing a notification. It's like the background service and the notification messages are working hand in hand, and cannot be apart from each other. Is there a way to change this?

Thank you!

**Comment by nicolas-garcia** [comment]
Hi!

What are you trying to achieve ?
Are you working on Android?

If so, the way background services are implemented on Android is using Foreground Service ([doc](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/foreground-services)), and you **MUST** display a notification on the device when using foreground service. In fact, the native API require a notification for starting the service.

Some links:
- [Is there a way to start foreground service without showing a notification for Android 8.0 and above versions?](https://stackoverflow.com/questions/54774705/is-there-a-way-to-start-foreground-service-without-showing-a-notification-for-an)
- [Hiding foreground services notifications in Android](https://www.spiria.com/en/blog/mobile-development/hiding-foreground-services-notifications-in-android/)

**Comment by Dax-Ur** [comment]
Yes, I'm working on Android right now, but I'd like to work with iOS too. What I'm trying to do is reading a string value generated by a server once per hour, and if the value = 1, the app shows a notification, if the value = 0, it does nothing.
